### ISSUE TITLE
Improvement for non-user-friendly definitions

### ISSUE THREAD

**Issue by harunyasar** [harunyasar/odooclient#8]
@joel-depiltech 
When I want to create a new query on Odoo before I have to make this domain filter definition:

```php
$domain_filter = array (
        new xmlrpcval(
            array(new xmlrpcval('is_company' , 'string'),
                  new xmlrpcval('!=', 'string'),
                  new xmlrpcval('True', 'string')
            ), 'array'
        ),
);

$client->search('res.partner', $domain_filter);
```

I think this usage is not user friendly. I wrote a new concept (code snippet) for this usage for replacing with it in the future. What do you think about it?

```php
$filter = new Filter();

$element = new Element();
$element->setField('is_company');
$element->setComparison('=');
$element->setValue(True);

$filter->add($element);

$client->search('res.partner', $filter);
```

**Comment by joel-depiltech** [comment]
Hey harunyasar,

Sorry I was in a meeting.

That’s a good idea but this can be very difficult because the syntax is complex 

Can we talk about this on Monday, so I will the time to think about it ?

Regards,
Joël

**Comment by harunyasar** [comment]
Sure. Take care ;)

**Comment by joel-depiltech** [comment]
Hello @harunyasar,
Sorry I forgot to reply to you. That's a f****ng good idea !
In our company we use something very close and yesterday I added a method like this : 

```php
$parameter = new Parameter();
$parameter->setOffset(5);
$parameter->setLimit(15);
$parameter->setFields(array('display_name', 'code'));

$client->search_read('res.country', array(), $parameter);
```

**Comment by harunyasar** [comment]
If you improve this issue go ahead :)
